### ISSUE TITLE
--dryrun

### ISSUE THREAD

**Issue by erikbra** [erikbra/grate#33]
Just print out what would have been done, don't do it.

Is it as simple as adding another parameter to this method? 
```   
async Task LogAndRunSql()
            {
                _logger.LogInformation(" Running {scriptName} on {serverName} - {databaseName}.", scriptName, Database.ServerName, Database.DatabaseName);
                await RunTheActualSql(sql, scriptName, migrationType, versionId, connectionType);
                theSqlRun = true;
            }
```
            
## Tasks: 

- [ ] Do not copy the scripts to output folder on dryrun
- [ ] Do not run the scripts
- [ ] Do not record the scripts as run
- [ ] DO output the scripts as run
- [ ] DO compare the scripts with existing, perform all the logic, etc
